export const TYPES = {
    LEER_ESTADO: "LEER_ESTADO",
    METER_AL_CARRITO: "METER_AL_CARRITO",
    SACAR_DEL_CARRITO: "SACAR_DEL_CARRITO",
    SACAR_TODO_ITEM: "SACAR_TODO_ITEM",
    LIMPIAR_CARRITO: "LIMPIAR_CARRITO",
    CONTADOR_PRODUCTOS: "CONTADOR_PRODUCTOS"
};